version: "3.3"
services:
  pirate-hunt:
    build: .
    container_name: pirate-treasure-hunt
    ports:
      - "8000:8000"
    volumes:
      # Mount game data for persistence
      - ./game-data.json:/app/game-data.json
      # Mount config for easy updates
      - ./config.json:/app/config.json
      # Mount game rules for easy updates
      - ./game-rules.md:/app/game-rules.md
      # Mount quest rules for easy updates
      - ./quest-rules.md:/app/quest-rules.md
    restart: unless-stopped
    environment:
      - NODE_ENV=production
